---

api_id: API_ID
api_hash: API_HASH
app_short_name: APP_SHORT_NAME

messages:
  one: |
    this is message 1
    it can be whatever you want it to be
  two: |
    this is message 2
    again, it can be whatever you want it to be
    so you can have some variation

raid:
  CHANNEL_NAME:
    message_type: one
    # this is in seconds, so the below example is equal to 3 seconds
    # we recommend at least 900 seconds, which is equal to 15 minutes
    wait_interval: 3
  SOME_OTHER_CHANNEL_NAME:
    message_type: two
    # this is in seconds, so the below example is equal to 5 minutes
    # we recommend at least 900 seconds, which is equal to 15 minutes
    wait_interval: 300
    # this is in seconds, so the below example is equal to 1 minute
    increase_wait_interval: 60
    # this assumes the image's path is relative to the script `tg_shill_bot.py`
    image: images/cd.jpg
