---

api_id: API_ID
api_hash: API_HASH
app_short_name: APP_SHORT_NAME
phone_number: "PHONE_NUMBER"
# this has to be in quotes to ensure it is treated as a string
# e.g. phone_number: "+18888675309"

splay: 7
# configurable randomness of when channels connect and messages are sent;
# we recommend increasing this number when connecting to many (10+)
# channels to avoid the dreaded FloodWaitError; it is preferable to use
# prime numbers for maximum randomness

messages:
  one: |
    this is message 1
    it can be whatever you want it to be
  two: |
    this is message 2
    again, it can be whatever you want it to be
    so you can have some variation

raid:
  CHANNEL_NAME:
    message_type: one
    # this is in seconds, so the below example is equal to 3 seconds
    # we recommend at least 900 seconds, which is equal to 15 minutes
    wait_interval: 3
  SOME_OTHER_CHANNEL_NAME:
    # a channel can send multiple message types, so the below example will send messages `one` and `two`
    # the bot will send one message per wait interval in sequence
    message_type:
    - one
    - two
    # this is in seconds, so the below example is equal to 5 minutes
    # we recommend at least 900 seconds, which is equal to 15 minutes
    wait_interval: 300
    # this is in seconds, so the below example is equal to 1 minute
    increase_wait_interval: 60
    # a channel can limit the total number of messages sent, so the below example will send a maximum of 10 messages
    total_messages: 10
    # this assumes the image's path is relative to the script `tg_shill_bot.py`
    image: images/cd.jpg

########################################################
### !! DANGER ZONE !!
### >> only config below if you know what you are doing
########################################################
# this is a Python lambda function -- it is used to construct a formatted message that
# takes 2 inputs (random message 1 & random message 2) and returns a single string that
# is appened to your primary message
# this lambda will be eval'ed during runtime, so please becareful and know what you are doing
# before modifying
random_message_format: |
  lambda rm1, rm2 : rm1 + " & " + rm2 + "!"

# this is a list of random "thank yous" that will be used to create a random message
# that will be appended to your primary message to avoid TG banning -- SEE FAQs
random_message:
- Cheers
- Thank you
- Thank you so much
- Thanks
- Thanks a bunch
- Thanks a million
- Ta
- Tak
- Dank u
- Kiitos
- Merci
- Merci beaucoup
- Danke
- Danke sch√∂n
- Danke vielmals
- Mahalo
- Grazie
- Arigato
- Obrigado
- Gracias
- Xie xie
- Shukran
- Hvala
- Efharisto
- Dhanyavaad
- Spasiba
- Salamat
- Khob khun
