---

api_id: API_ID
api_hash: API_HASH
app_short_name: APP_SHORT_NAME
phone_number: "PHONE_NUMBER"
# this has to be in quotes to ensure it is treated as a string
# e.g. phone_number: "+18888675309"

messages:
  one: |
    this is message 1
    it can be whatever you want it to be
  two: |
    this is message 2
    again, it can be whatever you want it to be
    so you can have some variation

raid:
  CHANNEL_NAME:
    message_type: one
    # this is in seconds, so the below example is equal to 3 seconds
    # we recommend at least 900 seconds, which is equal to 15 minutes
    wait_interval: 3
  SOME_OTHER_CHANNEL_NAME:
    # a channel can send multiple message types, so the below example will send messages `one` and `two`
    # the bot will send one message per wait interval in sequence
    message_type:
    - one
    - two
    # this is in seconds, so the below example is equal to 5 minutes
    # we recommend at least 900 seconds, which is equal to 15 minutes
    wait_interval: 300
    # this is in seconds, so the below example is equal to 1 minute
    increase_wait_interval: 60
    # a channel can limit the total number of messages sent, so the below example will send a maximum of 10 messages
    total_messages: 10
    # this assumes the image's path is relative to the script `tg_shill_bot.py`
    image: images/cd.jpg
